monolog:
    channels: ['trade']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            channels: ['!event']
        trade:
            type: stream
            path: '%kernel.logs_dir%/trade.log'
            level: info
            channels: ['trade']
